# Add labels to PRs based on file changes
app.py:
  - changed-files:
    - any-glob-to-any-file: app.py

docker:
  - changed-files:
    - any-glob-to-any-file: Dockerfile
    - any-glob-to-any-file: docker-compose.yml

github-actions:
  - changed-files:
    - any-glob-to-any-file: .github/workflows/*

documentation:
  - changed-files:
    - any-glob-to-any-file: README.md
    - any-glob-to-any-file: docs/*
